### ISSUE TITLE
Docs: include detail on meaning of command outputs where helpful

### ISSUE THREAD

**Issue by kd-ods** [openownership/bodskit#10]
Would be good to have a bit of detail in the docs about the meaning of command outputs where it might not be obvious. For example on the [mapping-sheet page](https://bodskit.readthedocs.io/en/master/cli-mapping-sheet.html), explain what each of the columns in the outputted CSV represents:

- section
- path
- title
- description
- type
- range
- values
- links
- deprecated
- deprecationNotes

**Comment by jpmckinney** [comment]
This is documented in OCDS Kit here: https://ocdskit.readthedocs.io/en/latest/api/mapping_sheet.html#ocdskit.mapping_sheet.mapping_sheet

**Comment by stevenday** [comment]
Closing as we're archiving this repo
