### ISSUE TITLE
FYI, can use csvstack instead of all-codes

### ISSUE THREAD

**Issue by jpmckinney** [openownership/bodskit#13]
```
pip install csvkit
cd path/to/data-standard
csvstack --filenames -n codelist schema/codelists/* | sed s/\.csv// | in2csv -f csv 
```

Produces the same file.

Note: ` | sed s/\.csv//` removes the `.csv` extension from the first column. ` | in2csv -f csv` ensures all rows have the same number of columns. Neither is strictly necessary for the use case.

**Comment by stevenday** [comment]
Closing as we're archiving this repo
