### ISSUE TITLE
FYI, ocdskit mapping-sheet produces same output as bodskit

### ISSUE THREAD

**Issue by jpmckinney** [openownership/bodskit#14]
I noticed there were only about six lines different, so I merged those changes into the next version of OCDS Kit, while making changes to support OC4IDS. The command also works with SEDL. We can try to just update one bit of code instead of copying repositories.

(Note: You need to use `--order-by path` and `--infer-required` to get the same output as the test fixture. Drop `--infer-required` to fix #9.)

Similarly, ocdskit schema-report now also supports BODS with only stylistic changes in output, which can easily be changed if needed.

**Comment by Bjwebb** [comment]
Along with https://github.com/openownership/bodskit/issues/13, this means that all of bodskit could be replaced with other commands.

So, we might want to archive bodskit, and replace our usage with other commands. We should check who's run bodskit recently, and which commands (I get the impression some are not frequently run), and which bits of the output they rely on. I can't see it running in automated builds anywhere.

@jpmckinney and @odscjames might also have some ideas of other ocdskit subcommands that would be useful for BODS.

**Comment by jpmckinney** [comment]
All the non-OCDS commands are documented here (besides the [indent command](https://ocdskit.readthedocs.io/en/latest/cli/generic.html)): https://ocdskit.readthedocs.io/en/latest/cli/schema.html

**Comment by stevenday** [comment]
Closing as we're archiving this repo.

Thanks @jpmckinney for pointing out the issues here
