### ISSUE TITLE
mapping-sheet: 'range' values not as expected

### ISSUE THREAD

**Issue by kd-ods** [openownership/bodskit#9]
Range should indicate the number of values required by a field.

For example, looking at [person-statement.json](https://github.com/openownership/data-standard/blob/schema-beta-2/schema/person-statement.json), when the mapping-sheet command is used one would expect that - of the top level fields - only statementID and statementType would have range 1..1 (i.e. a single value is required). But optional like birthDate and deathDate are also given a range of 1..1 .

(Requirements-wise, could we please indicate sub-property ranges with brackets around the range value. So, for example we would end up with:

,identifiers,Identifiers,"One or more official identifiers for this perrson. Where available, official registration numbers should be provided.",array,0..n,,,,
,identifiers,Identifier,An identifier that has been assigned to this entity. The scheme or list from which the identifier is drawn should be declared.,object,,,,,
identifiers,identifiers/id,ID,The identifier for this entity as provided in the declared scheme.,string,(0..1),,,,
identifiers,identifiers/scheme,Scheme,"For entity statements, the scheme should be a entry from the org-id.guide codelist. For person statements, recognised values include 'passport', 'internal' and 'id-card'.",string,(0..1),,http://www.org-id.guide,,
identifiers,identifiers/schemeName,Scheme name,,string,(0..1),,,,
identifiers,identifiers/uri,URI,Where this identifier has a canonical URI this may be included,string,(0..1),uri,https://en.wikipedia.org/wiki/Uniform_Resource_Identifier,,
)

**Comment by jpmckinney** [comment]
This is fixed in `ocdskit mapping-sheet`, which also works on BODS schema (it's the same style of schema as OCDS).

**Comment by stevenday** [comment]
Closing as we're archiving this repo
